"""empty message

Revision ID: fdf8490f0a0c
Revises: 00ffc828019b
Create Date: 2022-07-06 17:05:05.939842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf8490f0a0c'
down_revision = '00ffc828019b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('val', sa.String(length=255), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('_type', sa.Enum('static', 'dynamic'), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['t_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_attribute')
    # ### end Alembic commands ###
